#!/usr/bin/env python3
"""poison video — SVG/PNG frames in, animated explainer MP4 out, via Remotion.

  poison_video.py --title "How DNS works" --frames frames.json --out ./ --prefix poison [--narrate]

frames.json is a list of {"image": "path.svg|png", "caption": "...", "narration": "..."}.
Each frame gets a fade-in, a gentle settle, a caption pill, and (with --narrate) a spoken
line generated by macOS `say` (free, offline); frame length follows the narration, else
--seconds-per-frame. Prints one JSON line {"path", "frames", "durationSec", "cost": 0}.
Exit 2 = setup problem, exit 1 = render failed.
"""
import argparse
import glob
import json
import os
import shutil
import subprocess
import sys
import wave

HERE = os.path.dirname(os.path.abspath(__file__))
VIDEO_DIR = os.path.join(os.path.dirname(HERE), "video")
FPS = 30


def die(code, msg):
    print(f"poison-video: {msg}", file=sys.stderr)
    sys.exit(code)


def ensure_deps():
    if not shutil.which("npx"):
        die(2, "node/npm not found; install Node 20+ (brew install node)")
    if not os.path.isdir(os.path.join(VIDEO_DIR, "node_modules", "remotion")):
        print("poison-video: installing Remotion (first run, a few hundred MB)...", file=sys.stderr)
        r = subprocess.run(["npm", "install", "--no-audit", "--no-fund"], cwd=VIDEO_DIR)
        if r.returncode:
            die(2, "npm install failed inside skill/video")


def browser_executable():
    """Reuse a Chromium already on disk so Remotion does not download its own."""
    cands = [
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Chromium.app/Contents/MacOS/Chromium",
    ]
    for base in ("~/Library/Caches/ms-playwright", "~/.cache/ms-playwright"):
        cands += sorted(glob.glob(os.path.expanduser(base + "/chromium-*/chrome-mac*/Chromium.app/Contents/MacOS/Chromium")), reverse=True)
        cands += sorted(glob.glob(os.path.expanduser(base + "/chromium_headless_shell-*/chrome-headless-shell-*/chrome-headless-shell")), reverse=True)
    for c in cands:
        if os.path.exists(c):
            return c
    return None


def wav_seconds(path):
    with wave.open(path, "rb") as w:
        return w.getnframes() / float(w.getframerate())


def narrate(text, out_wav, voice):
    cmd = ["say", "-v", voice, "--data-format=LEI16@22050", "-o", out_wav, text]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        die(2, f"say failed: {r.stderr.strip()}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--frames", required=True, help="json list of {image, caption, narration}")
    ap.add_argument("--title", default="poison")
    ap.add_argument("--out", default=".")
    ap.add_argument("--prefix", default="poison")
    ap.add_argument("--narrate", action="store_true", help="speak each frame's narration with macOS say")
    ap.add_argument("--voice", default="Samantha")
    ap.add_argument("--seconds-per-frame", type=float, default=4.0)
    ap.add_argument("--transition", type=float, default=0.6)
    ap.add_argument("--width", type=int, default=1536)
    ap.add_argument("--height", type=int, default=1024)
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()

    frames = json.load(open(a.frames))
    if not frames:
        die(2, "frames list is empty")
    base = os.path.dirname(os.path.abspath(a.frames))
    for f in frames:
        # relative image paths are relative to the frames file, not the cwd
        if not os.path.isabs(f["image"]):
            f["image"] = os.path.join(base, f["image"])
        if not os.path.exists(f["image"]):
            die(2, f"frame image not found: {f['image']}")
    if a.narrate and sys.platform != "darwin":
        die(2, "--narrate uses macOS say; drop the flag or add your own wav per frame")

    job = os.path.join(VIDEO_DIR, "public", "job")
    if a.dry_run:
        print(json.dumps({"frames": len(frames), "browser": browser_executable(), "video_dir": VIDEO_DIR}))
        return

    ensure_deps()
    shutil.rmtree(job, ignore_errors=True)
    os.makedirs(job)
    props_frames = []
    for i, f in enumerate(frames, 1):
        ext = os.path.splitext(f["image"])[1].lower() or ".svg"
        name = f"frame-{i}{ext}"
        shutil.copy(f["image"], os.path.join(job, name))
        entry = {"image": f"job/{name}", "caption": f.get("caption", ""), "durationSec": a.seconds_per_frame}
        text = (f.get("narration") or f.get("caption") or "").strip()
        if a.narrate and text:
            wav = os.path.join(job, f"narration-{i}.wav")
            narrate(text, wav, a.voice)
            entry["audio"] = f"job/narration-{i}.wav"
            entry["durationSec"] = round(wav_seconds(wav) + 0.9, 2)
        props_frames.append(entry)

    props = {"width": a.width, "height": a.height, "title": a.title,
             "frames": props_frames, "transitionSec": a.transition, "tailSec": 1.5}
    props_path = os.path.join(job, "props.json")
    json.dump(props, open(props_path, "w"))

    os.makedirs(a.out, exist_ok=True)
    out_path = os.path.abspath(os.path.join(a.out, f"{a.prefix}.mp4"))
    cmd = ["npx", "remotion", "render", "src/index.ts", "Explainer", out_path,
           f"--props={props_path}", "--log=error"]
    exe = browser_executable()
    if exe:
        cmd.append(f"--browser-executable={exe}")
    r = subprocess.run(cmd, cwd=VIDEO_DIR)
    if r.returncode or not os.path.exists(out_path):
        die(1, "remotion render failed (rerun without --log=error inside skill/video to see why)")
    total = 1 + sum(f["durationSec"] for f in props_frames) + 1.5
    print(json.dumps({"path": out_path, "frames": len(frames), "durationSec": round(total, 1),
                      "narrated": bool(a.narrate), "cost": 0}))


if __name__ == "__main__":
    main()
